scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'monitoring-demo'
    scrape_interval: 5s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['monitoring-demo:8080']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'mysqld'
    static_configs:
      - targets: ['mysqld-exporter:9104']